// Keysym to Unicode conversion table.
// Taken from xterm/keysym2ucs.c

#[allow(unreachable_patterns)]

pub const fn char_to_keysym_map(c: char) -> Option<u32> {
    match c {
        '\u{0104}' => Some(0x01a1), //                     Aogonek Ą LATIN CAPITAL LETTER A WITH OGONEK
        '\u{02d8}' => Some(0x01a2), //                       breve ˘ BREVE
        '\u{0141}' => Some(0x01a3), //                     Lstroke Ł LATIN CAPITAL LETTER L WITH STROKE
        '\u{013d}' => Some(0x01a5), //                      Lcaron Ľ LATIN CAPITAL LETTER L WITH CARON
        '\u{015a}' => Some(0x01a6), //                      Sacute Ś LATIN CAPITAL LETTER S WITH ACUTE
        '\u{0160}' => Some(0x01a9), //                      Scaron Š LATIN CAPITAL LETTER S WITH CARON
        '\u{015e}' => Some(0x01aa), //                    Scedilla Ş LATIN CAPITAL LETTER S WITH CEDILLA
        '\u{0164}' => Some(0x01ab), //                      Tcaron Ť LATIN CAPITAL LETTER T WITH CARON
        '\u{0179}' => Some(0x01ac), //                      Zacute Ź LATIN CAPITAL LETTER Z WITH ACUTE
        '\u{017d}' => Some(0x01ae), //                      Zcaron Ž LATIN CAPITAL LETTER Z WITH CARON
        '\u{017b}' => Some(0x01af), //                   Zabovedot Ż LATIN CAPITAL LETTER Z WITH DOT ABOVE
        '\u{0105}' => Some(0x01b1), //                     aogonek ą LATIN SMALL LETTER A WITH OGONEK
        '\u{02db}' => Some(0x01b2), //                      ogonek ˛ OGONEK
        '\u{0142}' => Some(0x01b3), //                     lstroke ł LATIN SMALL LETTER L WITH STROKE
        '\u{013e}' => Some(0x01b5), //                      lcaron ľ LATIN SMALL LETTER L WITH CARON
        '\u{015b}' => Some(0x01b6), //                      sacute ś LATIN SMALL LETTER S WITH ACUTE
        '\u{02c7}' => Some(0x01b7), //                       caron ˇ CARON
        '\u{0161}' => Some(0x01b9), //                      scaron š LATIN SMALL LETTER S WITH CARON
        '\u{015f}' => Some(0x01ba), //                    scedilla ş LATIN SMALL LETTER S WITH CEDILLA
        '\u{0165}' => Some(0x01bb), //                      tcaron ť LATIN SMALL LETTER T WITH CARON
        '\u{017a}' => Some(0x01bc), //                      zacute ź LATIN SMALL LETTER Z WITH ACUTE
        '\u{02dd}' => Some(0x01bd), //                 doubleacute ˝ DOUBLE ACUTE ACCENT
        '\u{017e}' => Some(0x01be), //                      zcaron ž LATIN SMALL LETTER Z WITH CARON
        '\u{017c}' => Some(0x01bf), //                   zabovedot ż LATIN SMALL LETTER Z WITH DOT ABOVE
        '\u{0154}' => Some(0x01c0), //                      Racute Ŕ LATIN CAPITAL LETTER R WITH ACUTE
        '\u{0102}' => Some(0x01c3), //                      Abreve Ă LATIN CAPITAL LETTER A WITH BREVE
        '\u{0139}' => Some(0x01c5), //                      Lacute Ĺ LATIN CAPITAL LETTER L WITH ACUTE
        '\u{0106}' => Some(0x01c6), //                      Cacute Ć LATIN CAPITAL LETTER C WITH ACUTE
        '\u{010c}' => Some(0x01c8), //                      Ccaron Č LATIN CAPITAL LETTER C WITH CARON
        '\u{0118}' => Some(0x01ca), //                     Eogonek Ę LATIN CAPITAL LETTER E WITH OGONEK
        '\u{011a}' => Some(0x01cc), //                      Ecaron Ě LATIN CAPITAL LETTER E WITH CARON
        '\u{010e}' => Some(0x01cf), //                      Dcaron Ď LATIN CAPITAL LETTER D WITH CARON
        '\u{0110}' => Some(0x01d0), //                     Dstroke Đ LATIN CAPITAL LETTER D WITH STROKE
        '\u{0143}' => Some(0x01d1), //                      Nacute Ń LATIN CAPITAL LETTER N WITH ACUTE
        '\u{0147}' => Some(0x01d2), //                      Ncaron Ň LATIN CAPITAL LETTER N WITH CARON
        '\u{0150}' => Some(0x01d5), //                Odoubleacute Ő LATIN CAPITAL LETTER O WITH DOUBLE ACUTE
        '\u{0158}' => Some(0x01d8), //                      Rcaron Ř LATIN CAPITAL LETTER R WITH CARON
        '\u{016e}' => Some(0x01d9), //                       Uring Ů LATIN CAPITAL LETTER U WITH RING ABOVE
        '\u{0170}' => Some(0x01db), //                Udoubleacute Ű LATIN CAPITAL LETTER U WITH DOUBLE ACUTE
        '\u{0162}' => Some(0x01de), //                    Tcedilla Ţ LATIN CAPITAL LETTER T WITH CEDILLA
        '\u{0155}' => Some(0x01e0), //                      racute ŕ LATIN SMALL LETTER R WITH ACUTE
        '\u{0103}' => Some(0x01e3), //                      abreve ă LATIN SMALL LETTER A WITH BREVE
        '\u{013a}' => Some(0x01e5), //                      lacute ĺ LATIN SMALL LETTER L WITH ACUTE
        '\u{0107}' => Some(0x01e6), //                      cacute ć LATIN SMALL LETTER C WITH ACUTE
        '\u{010d}' => Some(0x01e8), //                      ccaron č LATIN SMALL LETTER C WITH CARON
        '\u{0119}' => Some(0x01ea), //                     eogonek ę LATIN SMALL LETTER E WITH OGONEK
        '\u{011b}' => Some(0x01ec), //                      ecaron ě LATIN SMALL LETTER E WITH CARON
        '\u{010f}' => Some(0x01ef), //                      dcaron ď LATIN SMALL LETTER D WITH CARON
        '\u{0111}' => Some(0x01f0), //                     dstroke đ LATIN SMALL LETTER D WITH STROKE
        '\u{0144}' => Some(0x01f1), //                      nacute ń LATIN SMALL LETTER N WITH ACUTE
        '\u{0148}' => Some(0x01f2), //                      ncaron ň LATIN SMALL LETTER N WITH CARON
        '\u{0151}' => Some(0x01f5), //                odoubleacute ő LATIN SMALL LETTER O WITH DOUBLE ACUTE
        '\u{0159}' => Some(0x01f8), //                      rcaron ř LATIN SMALL LETTER R WITH CARON
        '\u{016f}' => Some(0x01f9), //                       uring ů LATIN SMALL LETTER U WITH RING ABOVE
        '\u{0171}' => Some(0x01fb), //                udoubleacute ű LATIN SMALL LETTER U WITH DOUBLE ACUTE
        '\u{0163}' => Some(0x01fe), //                    tcedilla ţ LATIN SMALL LETTER T WITH CEDILLA
        '\u{02d9}' => Some(0x01ff), //                    abovedot ˙ DOT ABOVE
        '\u{0126}' => Some(0x02a1), //                     Hstroke Ħ LATIN CAPITAL LETTER H WITH STROKE
        '\u{0124}' => Some(0x02a6), //                 Hcircumflex Ĥ LATIN CAPITAL LETTER H WITH CIRCUMFLEX
        '\u{0130}' => Some(0x02a9), //                   Iabovedot İ LATIN CAPITAL LETTER I WITH DOT ABOVE
        '\u{011e}' => Some(0x02ab), //                      Gbreve Ğ LATIN CAPITAL LETTER G WITH BREVE
        '\u{0134}' => Some(0x02ac), //                 Jcircumflex Ĵ LATIN CAPITAL LETTER J WITH CIRCUMFLEX
        '\u{0127}' => Some(0x02b1), //                     hstroke ħ LATIN SMALL LETTER H WITH STROKE
        '\u{0125}' => Some(0x02b6), //                 hcircumflex ĥ LATIN SMALL LETTER H WITH CIRCUMFLEX
        '\u{0131}' => Some(0x02b9), //                    idotless ı LATIN SMALL LETTER DOTLESS I
        '\u{011f}' => Some(0x02bb), //                      gbreve ğ LATIN SMALL LETTER G WITH BREVE
        '\u{0135}' => Some(0x02bc), //                 jcircumflex ĵ LATIN SMALL LETTER J WITH CIRCUMFLEX
        '\u{010a}' => Some(0x02c5), //                   Cabovedot Ċ LATIN CAPITAL LETTER C WITH DOT ABOVE
        '\u{0108}' => Some(0x02c6), //                 Ccircumflex Ĉ LATIN CAPITAL LETTER C WITH CIRCUMFLEX
        '\u{0120}' => Some(0x02d5), //                   Gabovedot Ġ LATIN CAPITAL LETTER G WITH DOT ABOVE
        '\u{011c}' => Some(0x02d8), //                 Gcircumflex Ĝ LATIN CAPITAL LETTER G WITH CIRCUMFLEX
        '\u{016c}' => Some(0x02dd), //                      Ubreve Ŭ LATIN CAPITAL LETTER U WITH BREVE
        '\u{015c}' => Some(0x02de), //                 Scircumflex Ŝ LATIN CAPITAL LETTER S WITH CIRCUMFLEX
        '\u{010b}' => Some(0x02e5), //                   cabovedot ċ LATIN SMALL LETTER C WITH DOT ABOVE
        '\u{0109}' => Some(0x02e6), //                 ccircumflex ĉ LATIN SMALL LETTER C WITH CIRCUMFLEX
        '\u{0121}' => Some(0x02f5), //                   gabovedot ġ LATIN SMALL LETTER G WITH DOT ABOVE
        '\u{011d}' => Some(0x02f8), //                 gcircumflex ĝ LATIN SMALL LETTER G WITH CIRCUMFLEX
        '\u{016d}' => Some(0x02fd), //                      ubreve ŭ LATIN SMALL LETTER U WITH BREVE
        '\u{015d}' => Some(0x02fe), //                 scircumflex ŝ LATIN SMALL LETTER S WITH CIRCUMFLEX
        '\u{0138}' => Some(0x03a2), //                         kra ĸ LATIN SMALL LETTER KRA
        '\u{0156}' => Some(0x03a3), //                    Rcedilla Ŗ LATIN CAPITAL LETTER R WITH CEDILLA
        '\u{0128}' => Some(0x03a5), //                      Itilde Ĩ LATIN CAPITAL LETTER I WITH TILDE
        '\u{013b}' => Some(0x03a6), //                    Lcedilla Ļ LATIN CAPITAL LETTER L WITH CEDILLA
        '\u{0112}' => Some(0x03aa), //                     Emacron Ē LATIN CAPITAL LETTER E WITH MACRON
        '\u{0122}' => Some(0x03ab), //                    Gcedilla Ģ LATIN CAPITAL LETTER G WITH CEDILLA
        '\u{0166}' => Some(0x03ac), //                      Tslash Ŧ LATIN CAPITAL LETTER T WITH STROKE
        '\u{0157}' => Some(0x03b3), //                    rcedilla ŗ LATIN SMALL LETTER R WITH CEDILLA
        '\u{0129}' => Some(0x03b5), //                      itilde ĩ LATIN SMALL LETTER I WITH TILDE
        '\u{013c}' => Some(0x03b6), //                    lcedilla ļ LATIN SMALL LETTER L WITH CEDILLA
        '\u{0113}' => Some(0x03ba), //                     emacron ē LATIN SMALL LETTER E WITH MACRON
        '\u{0123}' => Some(0x03bb), //                    gcedilla ģ LATIN SMALL LETTER G WITH CEDILLA
        '\u{0167}' => Some(0x03bc), //                      tslash ŧ LATIN SMALL LETTER T WITH STROKE
        '\u{014a}' => Some(0x03bd), //                         ENG Ŋ LATIN CAPITAL LETTER ENG
        '\u{014b}' => Some(0x03bf), //                         eng ŋ LATIN SMALL LETTER ENG
        '\u{0100}' => Some(0x03c0), //                     Amacron Ā LATIN CAPITAL LETTER A WITH MACRON
        '\u{012e}' => Some(0x03c7), //                     Iogonek Į LATIN CAPITAL LETTER I WITH OGONEK
        '\u{0116}' => Some(0x03cc), //                   Eabovedot Ė LATIN CAPITAL LETTER E WITH DOT ABOVE
        '\u{012a}' => Some(0x03cf), //                     Imacron Ī LATIN CAPITAL LETTER I WITH MACRON
        '\u{0145}' => Some(0x03d1), //                    Ncedilla Ņ LATIN CAPITAL LETTER N WITH CEDILLA
        '\u{014c}' => Some(0x03d2), //                     Omacron Ō LATIN CAPITAL LETTER O WITH MACRON
        '\u{0136}' => Some(0x03d3), //                    Kcedilla Ķ LATIN CAPITAL LETTER K WITH CEDILLA
        '\u{0172}' => Some(0x03d9), //                     Uogonek Ų LATIN CAPITAL LETTER U WITH OGONEK
        '\u{0168}' => Some(0x03dd), //                      Utilde Ũ LATIN CAPITAL LETTER U WITH TILDE
        '\u{016a}' => Some(0x03de), //                     Umacron Ū LATIN CAPITAL LETTER U WITH MACRON
        '\u{0101}' => Some(0x03e0), //                     amacron ā LATIN SMALL LETTER A WITH MACRON
        '\u{012f}' => Some(0x03e7), //                     iogonek į LATIN SMALL LETTER I WITH OGONEK
        '\u{0117}' => Some(0x03ec), //                   eabovedot ė LATIN SMALL LETTER E WITH DOT ABOVE
        '\u{012b}' => Some(0x03ef), //                     imacron ī LATIN SMALL LETTER I WITH MACRON
        '\u{0146}' => Some(0x03f1), //                    ncedilla ņ LATIN SMALL LETTER N WITH CEDILLA
        '\u{014d}' => Some(0x03f2), //                     omacron ō LATIN SMALL LETTER O WITH MACRON
        '\u{0137}' => Some(0x03f3), //                    kcedilla ķ LATIN SMALL LETTER K WITH CEDILLA
        '\u{0173}' => Some(0x03f9), //                     uogonek ų LATIN SMALL LETTER U WITH OGONEK
        '\u{0169}' => Some(0x03fd), //                      utilde ũ LATIN SMALL LETTER U WITH TILDE
        '\u{016b}' => Some(0x03fe), //                     umacron ū LATIN SMALL LETTER U WITH MACRON
        '\u{203e}' => Some(0x047e), //                    overline ‾ OVERLINE
        '\u{3002}' => Some(0x04a1), //               kana_fullstop 。 IDEOGRAPHIC FULL STOP
        '\u{300c}' => Some(0x04a2), //         kana_openingbracket 「 LEFT CORNER BRACKET
        '\u{300d}' => Some(0x04a3), //         kana_closingbracket 」 RIGHT CORNER BRACKET
        '\u{3001}' => Some(0x04a4), //                  kana_comma 、 IDEOGRAPHIC COMMA
        '\u{30fb}' => Some(0x04a5), //            kana_conjunctive ・ KATAKANA MIDDLE DOT
        '\u{30f2}' => Some(0x04a6), //                     kana_WO ヲ KATAKANA LETTER WO
        '\u{30a1}' => Some(0x04a7), //                      kana_a ァ KATAKANA LETTER SMALL A
        '\u{30a3}' => Some(0x04a8), //                      kana_i ィ KATAKANA LETTER SMALL I
        '\u{30a5}' => Some(0x04a9), //                      kana_u ゥ KATAKANA LETTER SMALL U
        '\u{30a7}' => Some(0x04aa), //                      kana_e ェ KATAKANA LETTER SMALL E
        '\u{30a9}' => Some(0x04ab), //                      kana_o ォ KATAKANA LETTER SMALL O
        '\u{30e3}' => Some(0x04ac), //                     kana_ya ャ KATAKANA LETTER SMALL YA
        '\u{30e5}' => Some(0x04ad), //                     kana_yu ュ KATAKANA LETTER SMALL YU
        '\u{30e7}' => Some(0x04ae), //                     kana_yo ョ KATAKANA LETTER SMALL YO
        '\u{30c3}' => Some(0x04af), //                    kana_tsu ッ KATAKANA LETTER SMALL TU
        '\u{30fc}' => Some(0x04b0), //              prolongedsound ー KATAKANA-HIRAGANA PROLONGED SOUND MARK
        '\u{30a2}' => Some(0x04b1), //                      kana_A ア KATAKANA LETTER A
        '\u{30a4}' => Some(0x04b2), //                      kana_I イ KATAKANA LETTER I
        '\u{30a6}' => Some(0x04b3), //                      kana_U ウ KATAKANA LETTER U
        '\u{30a8}' => Some(0x04b4), //                      kana_E エ KATAKANA LETTER E
        '\u{30aa}' => Some(0x04b5), //                      kana_O オ KATAKANA LETTER O
        '\u{30ab}' => Some(0x04b6), //                     kana_KA カ KATAKANA LETTER KA
        '\u{30ad}' => Some(0x04b7), //                     kana_KI キ KATAKANA LETTER KI
        '\u{30af}' => Some(0x04b8), //                     kana_KU ク KATAKANA LETTER KU
        '\u{30b1}' => Some(0x04b9), //                     kana_KE ケ KATAKANA LETTER KE
        '\u{30b3}' => Some(0x04ba), //                     kana_KO コ KATAKANA LETTER KO
        '\u{30b5}' => Some(0x04bb), //                     kana_SA サ KATAKANA LETTER SA
        '\u{30b7}' => Some(0x04bc), //                    kana_SHI シ KATAKANA LETTER SI
        '\u{30b9}' => Some(0x04bd), //                     kana_SU ス KATAKANA LETTER SU
        '\u{30bb}' => Some(0x04be), //                     kana_SE セ KATAKANA LETTER SE
        '\u{30bd}' => Some(0x04bf), //                     kana_SO ソ KATAKANA LETTER SO
        '\u{30bf}' => Some(0x04c0), //                     kana_TA タ KATAKANA LETTER TA
        '\u{30c1}' => Some(0x04c1), //                    kana_CHI チ KATAKANA LETTER TI
        '\u{30c4}' => Some(0x04c2), //                    kana_TSU ツ KATAKANA LETTER TU
        '\u{30c6}' => Some(0x04c3), //                     kana_TE テ KATAKANA LETTER TE
        '\u{30c8}' => Some(0x04c4), //                     kana_TO ト KATAKANA LETTER TO
        '\u{30ca}' => Some(0x04c5), //                     kana_NA ナ KATAKANA LETTER NA
        '\u{30cb}' => Some(0x04c6), //                     kana_NI ニ KATAKANA LETTER NI
        '\u{30cc}' => Some(0x04c7), //                     kana_NU ヌ KATAKANA LETTER NU
        '\u{30cd}' => Some(0x04c8), //                     kana_NE ネ KATAKANA LETTER NE
        '\u{30ce}' => Some(0x04c9), //                     kana_NO ノ KATAKANA LETTER NO
        '\u{30cf}' => Some(0x04ca), //                     kana_HA ハ KATAKANA LETTER HA
        '\u{30d2}' => Some(0x04cb), //                     kana_HI ヒ KATAKANA LETTER HI
        '\u{30d5}' => Some(0x04cc), //                     kana_FU フ KATAKANA LETTER HU
        '\u{30d8}' => Some(0x04cd), //                     kana_HE ヘ KATAKANA LETTER HE
        '\u{30db}' => Some(0x04ce), //                     kana_HO ホ KATAKANA LETTER HO
        '\u{30de}' => Some(0x04cf), //                     kana_MA マ KATAKANA LETTER MA
        '\u{30df}' => Some(0x04d0), //                     kana_MI ミ KATAKANA LETTER MI
        '\u{30e0}' => Some(0x04d1), //                     kana_MU ム KATAKANA LETTER MU
        '\u{30e1}' => Some(0x04d2), //                     kana_ME メ KATAKANA LETTER ME
        '\u{30e2}' => Some(0x04d3), //                     kana_MO モ KATAKANA LETTER MO
        '\u{30e4}' => Some(0x04d4), //                     kana_YA ヤ KATAKANA LETTER YA
        '\u{30e6}' => Some(0x04d5), //                     kana_YU ユ KATAKANA LETTER YU
        '\u{30e8}' => Some(0x04d6), //                     kana_YO ヨ KATAKANA LETTER YO
        '\u{30e9}' => Some(0x04d7), //                     kana_RA ラ KATAKANA LETTER RA
        '\u{30ea}' => Some(0x04d8), //                     kana_RI リ KATAKANA LETTER RI
        '\u{30eb}' => Some(0x04d9), //                     kana_RU ル KATAKANA LETTER RU
        '\u{30ec}' => Some(0x04da), //                     kana_RE レ KATAKANA LETTER RE
        '\u{30ed}' => Some(0x04db), //                     kana_RO ロ KATAKANA LETTER RO
        '\u{30ef}' => Some(0x04dc), //                     kana_WA ワ KATAKANA LETTER WA
        '\u{30f3}' => Some(0x04dd), //                      kana_N ン KATAKANA LETTER N
        '\u{309b}' => Some(0x04de), //                 voicedsound ゛ KATAKANA-HIRAGANA VOICED SOUND MARK
        '\u{309c}' => Some(0x04df), //             semivoicedsound ゜ KATAKANA-HIRAGANA SEMI-VOICED SOUND MARK
        '\u{060c}' => Some(0x05ac), //                Arabic_comma ، ARABIC COMMA
        '\u{061b}' => Some(0x05bb), //            Arabic_semicolon ؛ ARABIC SEMICOLON
        '\u{061f}' => Some(0x05bf), //        Arabic_question_mark ؟ ARABIC QUESTION MARK
        '\u{0621}' => Some(0x05c1), //                Arabic_hamza ء ARABIC LETTER HAMZA
        '\u{0622}' => Some(0x05c2), //          Arabic_maddaonalef آ ARABIC LETTER ALEF WITH MADDA ABOVE
        '\u{0623}' => Some(0x05c3), //          Arabic_hamzaonalef أ ARABIC LETTER ALEF WITH HAMZA ABOVE
        '\u{0624}' => Some(0x05c4), //           Arabic_hamzaonwaw ؤ ARABIC LETTER WAW WITH HAMZA ABOVE
        '\u{0625}' => Some(0x05c5), //       Arabic_hamzaunderalef إ ARABIC LETTER ALEF WITH HAMZA BELOW
        '\u{0626}' => Some(0x05c6), //           Arabic_hamzaonyeh ئ ARABIC LETTER YEH WITH HAMZA ABOVE
        '\u{0627}' => Some(0x05c7), //                 Arabic_alef ا ARABIC LETTER ALEF
        '\u{0628}' => Some(0x05c8), //                  Arabic_beh ب ARABIC LETTER BEH
        '\u{0629}' => Some(0x05c9), //           Arabic_tehmarbuta ة ARABIC LETTER TEH MARBUTA
        '\u{062a}' => Some(0x05ca), //                  Arabic_teh ت ARABIC LETTER TEH
        '\u{062b}' => Some(0x05cb), //                 Arabic_theh ث ARABIC LETTER THEH
        '\u{062c}' => Some(0x05cc), //                 Arabic_jeem ج ARABIC LETTER JEEM
        '\u{062d}' => Some(0x05cd), //                  Arabic_hah ح ARABIC LETTER HAH
        '\u{062e}' => Some(0x05ce), //                 Arabic_khah خ ARABIC LETTER KHAH
        '\u{062f}' => Some(0x05cf), //                  Arabic_dal د ARABIC LETTER DAL
        '\u{0630}' => Some(0x05d0), //                 Arabic_thal ذ ARABIC LETTER THAL
        '\u{0631}' => Some(0x05d1), //                   Arabic_ra ر ARABIC LETTER REH
        '\u{0632}' => Some(0x05d2), //                 Arabic_zain ز ARABIC LETTER ZAIN
        '\u{0633}' => Some(0x05d3), //                 Arabic_seen س ARABIC LETTER SEEN
        '\u{0634}' => Some(0x05d4), //                Arabic_sheen ش ARABIC LETTER SHEEN
        '\u{0635}' => Some(0x05d5), //                  Arabic_sad ص ARABIC LETTER SAD
        '\u{0636}' => Some(0x05d6), //                  Arabic_dad ض ARABIC LETTER DAD
        '\u{0637}' => Some(0x05d7), //                  Arabic_tah ط ARABIC LETTER TAH
        '\u{0638}' => Some(0x05d8), //                  Arabic_zah ظ ARABIC LETTER ZAH
        '\u{0639}' => Some(0x05d9), //                  Arabic_ain ع ARABIC LETTER AIN
        '\u{063a}' => Some(0x05da), //                Arabic_ghain غ ARABIC LETTER GHAIN
        '\u{0640}' => Some(0x05e0), //              Arabic_tatweel ـ ARABIC TATWEEL
        '\u{0641}' => Some(0x05e1), //                  Arabic_feh ف ARABIC LETTER FEH
        '\u{0642}' => Some(0x05e2), //                  Arabic_qaf ق ARABIC LETTER QAF
        '\u{0643}' => Some(0x05e3), //                  Arabic_kaf ك ARABIC LETTER KAF
        '\u{0644}' => Some(0x05e4), //                  Arabic_lam ل ARABIC LETTER LAM
        '\u{0645}' => Some(0x05e5), //                 Arabic_meem م ARABIC LETTER MEEM
        '\u{0646}' => Some(0x05e6), //                 Arabic_noon ن ARABIC LETTER NOON
        '\u{0647}' => Some(0x05e7), //                   Arabic_ha ه ARABIC LETTER HEH
        '\u{0648}' => Some(0x05e8), //                  Arabic_waw و ARABIC LETTER WAW
        '\u{0649}' => Some(0x05e9), //          Arabic_alefmaksura ى ARABIC LETTER ALEF MAKSURA
        '\u{064a}' => Some(0x05ea), //                  Arabic_yeh ي ARABIC LETTER YEH
        '\u{064b}' => Some(0x05eb), //             Arabic_fathatan ً ARABIC FATHATAN
        '\u{064c}' => Some(0x05ec), //             Arabic_dammatan ٌ ARABIC DAMMATAN
        '\u{064d}' => Some(0x05ed), //             Arabic_kasratan ٍ ARABIC KASRATAN
        '\u{064e}' => Some(0x05ee), //                Arabic_fatha َ ARABIC FATHA
        '\u{064f}' => Some(0x05ef), //                Arabic_damma ُ ARABIC DAMMA
        '\u{0650}' => Some(0x05f0), //                Arabic_kasra ِ ARABIC KASRA
        '\u{0651}' => Some(0x05f1), //               Arabic_shadda ّ ARABIC SHADDA
        '\u{0652}' => Some(0x05f2), //                Arabic_sukun ْ ARABIC SUKUN
        '\u{0452}' => Some(0x06a1), //                 Serbian_dje ђ CYRILLIC SMALL LETTER DJE
        '\u{0453}' => Some(0x06a2), //               Macedonia_gje ѓ CYRILLIC SMALL LETTER GJE
        '\u{0451}' => Some(0x06a3), //                 Cyrillic_io ё CYRILLIC SMALL LETTER IO
        '\u{0454}' => Some(0x06a4), //                Ukrainian_ie є CYRILLIC SMALL LETTER UKRAINIAN IE
        '\u{0455}' => Some(0x06a5), //               Macedonia_dse ѕ CYRILLIC SMALL LETTER DZE
        '\u{0456}' => Some(0x06a6), //                 Ukrainian_i і CYRILLIC SMALL LETTER BYELORUSSIAN-UKRAINIAN I
        '\u{0457}' => Some(0x06a7), //                Ukrainian_yi ї CYRILLIC SMALL LETTER YI
        '\u{0458}' => Some(0x06a8), //                 Cyrillic_je ј CYRILLIC SMALL LETTER JE
        '\u{0459}' => Some(0x06a9), //                Cyrillic_lje љ CYRILLIC SMALL LETTER LJE
        '\u{045a}' => Some(0x06aa), //                Cyrillic_nje њ CYRILLIC SMALL LETTER NJE
        '\u{045b}' => Some(0x06ab), //                Serbian_tshe ћ CYRILLIC SMALL LETTER TSHE
        '\u{045c}' => Some(0x06ac), //               Macedonia_kje ќ CYRILLIC SMALL LETTER KJE
        '\u{0491}' => Some(0x06ad), //   Ukrainian_ghe_with_upturn ґ CYRILLIC SMALL LETTER GHE WITH UPTURN
        '\u{045e}' => Some(0x06ae), //         Byelorussian_shortu ў CYRILLIC SMALL LETTER SHORT U
        '\u{045f}' => Some(0x06af), //               Cyrillic_dzhe џ CYRILLIC SMALL LETTER DZHE
        '\u{2116}' => Some(0x06b0), //                  numerosign № NUMERO SIGN
        '\u{0402}' => Some(0x06b1), //                 Serbian_DJE Ђ CYRILLIC CAPITAL LETTER DJE
        '\u{0403}' => Some(0x06b2), //               Macedonia_GJE Ѓ CYRILLIC CAPITAL LETTER GJE
        '\u{0401}' => Some(0x06b3), //                 Cyrillic_IO Ё CYRILLIC CAPITAL LETTER IO
        '\u{0404}' => Some(0x06b4), //                Ukrainian_IE Є CYRILLIC CAPITAL LETTER UKRAINIAN IE
        '\u{0405}' => Some(0x06b5), //               Macedonia_DSE Ѕ CYRILLIC CAPITAL LETTER DZE
        '\u{0406}' => Some(0x06b6), //                 Ukrainian_I І CYRILLIC CAPITAL LETTER BYELORUSSIAN-UKRAINIAN I
        '\u{0407}' => Some(0x06b7), //                Ukrainian_YI Ї CYRILLIC CAPITAL LETTER YI
        '\u{0408}' => Some(0x06b8), //                 Cyrillic_JE Ј CYRILLIC CAPITAL LETTER JE
        '\u{0409}' => Some(0x06b9), //                Cyrillic_LJE Љ CYRILLIC CAPITAL LETTER LJE
        '\u{040a}' => Some(0x06ba), //                Cyrillic_NJE Њ CYRILLIC CAPITAL LETTER NJE
        '\u{040b}' => Some(0x06bb), //                Serbian_TSHE Ћ CYRILLIC CAPITAL LETTER TSHE
        '\u{040c}' => Some(0x06bc), //               Macedonia_KJE Ќ CYRILLIC CAPITAL LETTER KJE
        '\u{0490}' => Some(0x06bd), //   Ukrainian_GHE_WITH_UPTURN Ґ CYRILLIC CAPITAL LETTER GHE WITH UPTURN
        '\u{040e}' => Some(0x06be), //         Byelorussian_SHORTU Ў CYRILLIC CAPITAL LETTER SHORT U
        '\u{040f}' => Some(0x06bf), //               Cyrillic_DZHE Џ CYRILLIC CAPITAL LETTER DZHE
        '\u{044e}' => Some(0x06c0), //                 Cyrillic_yu ю CYRILLIC SMALL LETTER YU
        '\u{0430}' => Some(0x06c1), //                  Cyrillic_a а CYRILLIC SMALL LETTER A
        '\u{0431}' => Some(0x06c2), //                 Cyrillic_be б CYRILLIC SMALL LETTER BE
        '\u{0446}' => Some(0x06c3), //                Cyrillic_tse ц CYRILLIC SMALL LETTER TSE
        '\u{0434}' => Some(0x06c4), //                 Cyrillic_de д CYRILLIC SMALL LETTER DE
        '\u{0435}' => Some(0x06c5), //                 Cyrillic_ie е CYRILLIC SMALL LETTER IE
        '\u{0444}' => Some(0x06c6), //                 Cyrillic_ef ф CYRILLIC SMALL LETTER EF
        '\u{0433}' => Some(0x06c7), //                Cyrillic_ghe г CYRILLIC SMALL LETTER GHE
        '\u{0445}' => Some(0x06c8), //                 Cyrillic_ha х CYRILLIC SMALL LETTER HA
        '\u{0438}' => Some(0x06c9), //                  Cyrillic_i и CYRILLIC SMALL LETTER I
        '\u{0439}' => Some(0x06ca), //             Cyrillic_shorti й CYRILLIC SMALL LETTER SHORT I
        '\u{043a}' => Some(0x06cb), //                 Cyrillic_ka к CYRILLIC SMALL LETTER KA
        '\u{043b}' => Some(0x06cc), //                 Cyrillic_el л CYRILLIC SMALL LETTER EL
        '\u{043c}' => Some(0x06cd), //                 Cyrillic_em м CYRILLIC SMALL LETTER EM
        '\u{043d}' => Some(0x06ce), //                 Cyrillic_en н CYRILLIC SMALL LETTER EN
        '\u{043e}' => Some(0x06cf), //                  Cyrillic_o о CYRILLIC SMALL LETTER O
        '\u{043f}' => Some(0x06d0), //                 Cyrillic_pe п CYRILLIC SMALL LETTER PE
        '\u{044f}' => Some(0x06d1), //                 Cyrillic_ya я CYRILLIC SMALL LETTER YA
        '\u{0440}' => Some(0x06d2), //                 Cyrillic_er р CYRILLIC SMALL LETTER ER
        '\u{0441}' => Some(0x06d3), //                 Cyrillic_es с CYRILLIC SMALL LETTER ES
        '\u{0442}' => Some(0x06d4), //                 Cyrillic_te т CYRILLIC SMALL LETTER TE
        '\u{0443}' => Some(0x06d5), //                  Cyrillic_u у CYRILLIC SMALL LETTER U
        '\u{0436}' => Some(0x06d6), //                Cyrillic_zhe ж CYRILLIC SMALL LETTER ZHE
        '\u{0432}' => Some(0x06d7), //                 Cyrillic_ve в CYRILLIC SMALL LETTER VE
        '\u{044c}' => Some(0x06d8), //           Cyrillic_softsign ь CYRILLIC SMALL LETTER SOFT SIGN
        '\u{044b}' => Some(0x06d9), //               Cyrillic_yeru ы CYRILLIC SMALL LETTER YERU
        '\u{0437}' => Some(0x06da), //                 Cyrillic_ze з CYRILLIC SMALL LETTER ZE
        '\u{0448}' => Some(0x06db), //                Cyrillic_sha ш CYRILLIC SMALL LETTER SHA
        '\u{044d}' => Some(0x06dc), //                  Cyrillic_e э CYRILLIC SMALL LETTER E
        '\u{0449}' => Some(0x06dd), //              Cyrillic_shcha щ CYRILLIC SMALL LETTER SHCHA
        '\u{0447}' => Some(0x06de), //                Cyrillic_che ч CYRILLIC SMALL LETTER CHE
        '\u{044a}' => Some(0x06df), //           Cyrillic_hardsign ъ CYRILLIC SMALL LETTER HARD SIGN
        '\u{042e}' => Some(0x06e0), //                 Cyrillic_YU Ю CYRILLIC CAPITAL LETTER YU
        '\u{0410}' => Some(0x06e1), //                  Cyrillic_A А CYRILLIC CAPITAL LETTER A
        '\u{0411}' => Some(0x06e2), //                 Cyrillic_BE Б CYRILLIC CAPITAL LETTER BE
        '\u{0426}' => Some(0x06e3), //                Cyrillic_TSE Ц CYRILLIC CAPITAL LETTER TSE
        '\u{0414}' => Some(0x06e4), //                 Cyrillic_DE Д CYRILLIC CAPITAL LETTER DE
        '\u{0415}' => Some(0x06e5), //                 Cyrillic_IE Е CYRILLIC CAPITAL LETTER IE
        '\u{0424}' => Some(0x06e6), //                 Cyrillic_EF Ф CYRILLIC CAPITAL LETTER EF
        '\u{0413}' => Some(0x06e7), //                Cyrillic_GHE Г CYRILLIC CAPITAL LETTER GHE
        '\u{0425}' => Some(0x06e8), //                 Cyrillic_HA Х CYRILLIC CAPITAL LETTER HA
        '\u{0418}' => Some(0x06e9), //                  Cyrillic_I И CYRILLIC CAPITAL LETTER I
        '\u{0419}' => Some(0x06ea), //             Cyrillic_SHORTI Й CYRILLIC CAPITAL LETTER SHORT I
        '\u{041a}' => Some(0x06eb), //                 Cyrillic_KA К CYRILLIC CAPITAL LETTER KA
        '\u{041b}' => Some(0x06ec), //                 Cyrillic_EL Л CYRILLIC CAPITAL LETTER EL
        '\u{041c}' => Some(0x06ed), //                 Cyrillic_EM М CYRILLIC CAPITAL LETTER EM
        '\u{041d}' => Some(0x06ee), //                 Cyrillic_EN Н CYRILLIC CAPITAL LETTER EN
        '\u{041e}' => Some(0x06ef), //                  Cyrillic_O О CYRILLIC CAPITAL LETTER O
        '\u{041f}' => Some(0x06f0), //                 Cyrillic_PE П CYRILLIC CAPITAL LETTER PE
        '\u{042f}' => Some(0x06f1), //                 Cyrillic_YA Я CYRILLIC CAPITAL LETTER YA
        '\u{0420}' => Some(0x06f2), //                 Cyrillic_ER Р CYRILLIC CAPITAL LETTER ER
        '\u{0421}' => Some(0x06f3), //                 Cyrillic_ES С CYRILLIC CAPITAL LETTER ES
        '\u{0422}' => Some(0x06f4), //                 Cyrillic_TE Т CYRILLIC CAPITAL LETTER TE
        '\u{0423}' => Some(0x06f5), //                  Cyrillic_U У CYRILLIC CAPITAL LETTER U
        '\u{0416}' => Some(0x06f6), //                Cyrillic_ZHE Ж CYRILLIC CAPITAL LETTER ZHE
        '\u{0412}' => Some(0x06f7), //                 Cyrillic_VE В CYRILLIC CAPITAL LETTER VE
        '\u{042c}' => Some(0x06f8), //           Cyrillic_SOFTSIGN Ь CYRILLIC CAPITAL LETTER SOFT SIGN
        '\u{042b}' => Some(0x06f9), //               Cyrillic_YERU Ы CYRILLIC CAPITAL LETTER YERU
        '\u{0417}' => Some(0x06fa), //                 Cyrillic_ZE З CYRILLIC CAPITAL LETTER ZE
        '\u{0428}' => Some(0x06fb), //                Cyrillic_SHA Ш CYRILLIC CAPITAL LETTER SHA
        '\u{042d}' => Some(0x06fc), //                  Cyrillic_E Э CYRILLIC CAPITAL LETTER E
        '\u{0429}' => Some(0x06fd), //              Cyrillic_SHCHA Щ CYRILLIC CAPITAL LETTER SHCHA
        '\u{0427}' => Some(0x06fe), //                Cyrillic_CHE Ч CYRILLIC CAPITAL LETTER CHE
        '\u{042a}' => Some(0x06ff), //           Cyrillic_HARDSIGN Ъ CYRILLIC CAPITAL LETTER HARD SIGN
        '\u{0386}' => Some(0x07a1), //           Greek_ALPHAaccent Ά GREEK CAPITAL LETTER ALPHA WITH TONOS
        '\u{0388}' => Some(0x07a2), //         Greek_EPSILONaccent Έ GREEK CAPITAL LETTER EPSILON WITH TONOS
        '\u{0389}' => Some(0x07a3), //             Greek_ETAaccent Ή GREEK CAPITAL LETTER ETA WITH TONOS
        '\u{038a}' => Some(0x07a4), //            Greek_IOTAaccent Ί GREEK CAPITAL LETTER IOTA WITH TONOS
        '\u{03aa}' => Some(0x07a5), //         Greek_IOTAdiaeresis Ϊ GREEK CAPITAL LETTER IOTA WITH DIALYTIKA
        '\u{038c}' => Some(0x07a7), //         Greek_OMICRONaccent Ό GREEK CAPITAL LETTER OMICRON WITH TONOS
        '\u{038e}' => Some(0x07a8), //         Greek_UPSILONaccent Ύ GREEK CAPITAL LETTER UPSILON WITH TONOS
        '\u{03ab}' => Some(0x07a9), //       Greek_UPSILONdieresis Ϋ GREEK CAPITAL LETTER UPSILON WITH DIALYTIKA
        '\u{038f}' => Some(0x07ab), //           Greek_OMEGAaccent Ώ GREEK CAPITAL LETTER OMEGA WITH TONOS
        '\u{0385}' => Some(0x07ae), //        Greek_accentdieresis ΅ GREEK DIALYTIKA TONOS
        '\u{2015}' => Some(0x07af), //              Greek_horizbar ― HORIZONTAL BAR
        '\u{03ac}' => Some(0x07b1), //           Greek_alphaaccent ά GREEK SMALL LETTER ALPHA WITH TONOS
        '\u{03ad}' => Some(0x07b2), //         Greek_epsilonaccent έ GREEK SMALL LETTER EPSILON WITH TONOS
        '\u{03ae}' => Some(0x07b3), //             Greek_etaaccent ή GREEK SMALL LETTER ETA WITH TONOS
        '\u{03af}' => Some(0x07b4), //            Greek_iotaaccent ί GREEK SMALL LETTER IOTA WITH TONOS
        '\u{03ca}' => Some(0x07b5), //          Greek_iotadieresis ϊ GREEK SMALL LETTER IOTA WITH DIALYTIKA
        '\u{0390}' => Some(0x07b6), //    Greek_iotaaccentdieresis ΐ GREEK SMALL LETTER IOTA WITH DIALYTIKA AND TONOS
        '\u{03cc}' => Some(0x07b7), //         Greek_omicronaccent ό GREEK SMALL LETTER OMICRON WITH TONOS
        '\u{03cd}' => Some(0x07b8), //         Greek_upsilonaccent ύ GREEK SMALL LETTER UPSILON WITH TONOS
        '\u{03cb}' => Some(0x07b9), //       Greek_upsilondieresis ϋ GREEK SMALL LETTER UPSILON WITH DIALYTIKA
        '\u{03b0}' => Some(0x07ba), // Greek_upsilonaccentdieresis ΰ GREEK SMALL LETTER UPSILON WITH DIALYTIKA AND TONOS
        '\u{03ce}' => Some(0x07bb), //           Greek_omegaaccent ώ GREEK SMALL LETTER OMEGA WITH TONOS
        '\u{0391}' => Some(0x07c1), //                 Greek_ALPHA Α GREEK CAPITAL LETTER ALPHA
        '\u{0392}' => Some(0x07c2), //                  Greek_BETA Β GREEK CAPITAL LETTER BETA
        '\u{0393}' => Some(0x07c3), //                 Greek_GAMMA Γ GREEK CAPITAL LETTER GAMMA
        '\u{0394}' => Some(0x07c4), //                 Greek_DELTA Δ GREEK CAPITAL LETTER DELTA
        '\u{0395}' => Some(0x07c5), //               Greek_EPSILON Ε GREEK CAPITAL LETTER EPSILON
        '\u{0396}' => Some(0x07c6), //                  Greek_ZETA Ζ GREEK CAPITAL LETTER ZETA
        '\u{0397}' => Some(0x07c7), //                   Greek_ETA Η GREEK CAPITAL LETTER ETA
        '\u{0398}' => Some(0x07c8), //                 Greek_THETA Θ GREEK CAPITAL LETTER THETA
        '\u{0399}' => Some(0x07c9), //                  Greek_IOTA Ι GREEK CAPITAL LETTER IOTA
        '\u{039a}' => Some(0x07ca), //                 Greek_KAPPA Κ GREEK CAPITAL LETTER KAPPA
        '\u{039b}' => Some(0x07cb), //                Greek_LAMBDA Λ GREEK CAPITAL LETTER LAMDA
        '\u{039c}' => Some(0x07cc), //                    Greek_MU Μ GREEK CAPITAL LETTER MU
        '\u{039d}' => Some(0x07cd), //                    Greek_NU Ν GREEK CAPITAL LETTER NU
        '\u{039e}' => Some(0x07ce), //                    Greek_XI Ξ GREEK CAPITAL LETTER XI
        '\u{039f}' => Some(0x07cf), //               Greek_OMICRON Ο GREEK CAPITAL LETTER OMICRON
        '\u{03a0}' => Some(0x07d0), //                    Greek_PI Π GREEK CAPITAL LETTER PI
        '\u{03a1}' => Some(0x07d1), //                   Greek_RHO Ρ GREEK CAPITAL LETTER RHO
        '\u{03a3}' => Some(0x07d2), //                 Greek_SIGMA Σ GREEK CAPITAL LETTER SIGMA
        '\u{03a4}' => Some(0x07d4), //                   Greek_TAU Τ GREEK CAPITAL LETTER TAU
        '\u{03a5}' => Some(0x07d5), //               Greek_UPSILON Υ GREEK CAPITAL LETTER UPSILON
        '\u{03a6}' => Some(0x07d6), //                   Greek_PHI Φ GREEK CAPITAL LETTER PHI
        '\u{03a7}' => Some(0x07d7), //                   Greek_CHI Χ GREEK CAPITAL LETTER CHI
        '\u{03a8}' => Some(0x07d8), //                   Greek_PSI Ψ GREEK CAPITAL LETTER PSI
        '\u{03a9}' => Some(0x07d9), //                 Greek_OMEGA Ω GREEK CAPITAL LETTER OMEGA
        '\u{03b1}' => Some(0x07e1), //                 Greek_alpha α GREEK SMALL LETTER ALPHA
        '\u{03b2}' => Some(0x07e2), //                  Greek_beta β GREEK SMALL LETTER BETA
        '\u{03b3}' => Some(0x07e3), //                 Greek_gamma γ GREEK SMALL LETTER GAMMA
        '\u{03b4}' => Some(0x07e4), //                 Greek_delta δ GREEK SMALL LETTER DELTA
        '\u{03b5}' => Some(0x07e5), //               Greek_epsilon ε GREEK SMALL LETTER EPSILON
        '\u{03b6}' => Some(0x07e6), //                  Greek_zeta ζ GREEK SMALL LETTER ZETA
        '\u{03b7}' => Some(0x07e7), //                   Greek_eta η GREEK SMALL LETTER ETA
        '\u{03b8}' => Some(0x07e8), //                 Greek_theta θ GREEK SMALL LETTER THETA
        '\u{03b9}' => Some(0x07e9), //                  Greek_iota ι GREEK SMALL LETTER IOTA
        '\u{03ba}' => Some(0x07ea), //                 Greek_kappa κ GREEK SMALL LETTER KAPPA
        '\u{03bb}' => Some(0x07eb), //                Greek_lambda λ GREEK SMALL LETTER LAMDA
        '\u{03bc}' => Some(0x07ec), //                    Greek_mu μ GREEK SMALL LETTER MU
        '\u{03bd}' => Some(0x07ed), //                    Greek_nu ν GREEK SMALL LETTER NU
        '\u{03be}' => Some(0x07ee), //                    Greek_xi ξ GREEK SMALL LETTER XI
        '\u{03bf}' => Some(0x07ef), //               Greek_omicron ο GREEK SMALL LETTER OMICRON
        '\u{03c0}' => Some(0x07f0), //                    Greek_pi π GREEK SMALL LETTER PI
        '\u{03c1}' => Some(0x07f1), //                   Greek_rho ρ GREEK SMALL LETTER RHO
        '\u{03c3}' => Some(0x07f2), //                 Greek_sigma σ GREEK SMALL LETTER SIGMA
        '\u{03c2}' => Some(0x07f3), //       Greek_finalsmallsigma ς GREEK SMALL LETTER FINAL SIGMA
        '\u{03c4}' => Some(0x07f4), //                   Greek_tau τ GREEK SMALL LETTER TAU
        '\u{03c5}' => Some(0x07f5), //               Greek_upsilon υ GREEK SMALL LETTER UPSILON
        '\u{03c6}' => Some(0x07f6), //                   Greek_phi φ GREEK SMALL LETTER PHI
        '\u{03c7}' => Some(0x07f7), //                   Greek_chi χ GREEK SMALL LETTER CHI
        '\u{03c8}' => Some(0x07f8), //                   Greek_psi ψ GREEK SMALL LETTER PSI
        '\u{03c9}' => Some(0x07f9), //                 Greek_omega ω GREEK SMALL LETTER OMEGA
        '\u{23b7}' => Some(0x08a1), //                 leftradical ⎷ RADICAL SYMBOL BOTTOM
        '\u{250c}' => Some(0x08a2), //              topleftradical ┌ BOX DRAWINGS LIGHT DOWN AND RIGHT
        '\u{2500}' => Some(0x08a3), //              horizconnector ─ BOX DRAWINGS LIGHT HORIZONTAL
        '\u{2320}' => Some(0x08a4), //                 topintegral ⌠ TOP HALF INTEGRAL
        '\u{2321}' => Some(0x08a5), //                 botintegral ⌡ BOTTOM HALF INTEGRAL
        '\u{2502}' => Some(0x08a6), //               vertconnector │ BOX DRAWINGS LIGHT VERTICAL
        '\u{23a1}' => Some(0x08a7), //            topleftsqbracket ⎡ LEFT SQUARE BRACKET UPPER CORNER
        '\u{23a3}' => Some(0x08a8), //            botleftsqbracket ⎣ LEFT SQUARE BRACKET LOWER CORNER
        '\u{23a4}' => Some(0x08a9), //           toprightsqbracket ⎤ RIGHT SQUARE BRACKET UPPER CORNER
        '\u{23a6}' => Some(0x08aa), //           botrightsqbracket ⎦ RIGHT SQUARE BRACKET LOWER CORNER
        '\u{239b}' => Some(0x08ab), //               topleftparens ⎛ LEFT PARENTHESIS UPPER HOOK
        '\u{239d}' => Some(0x08ac), //               botleftparens ⎝ LEFT PARENTHESIS LOWER HOOK
        '\u{239e}' => Some(0x08ad), //              toprightparens ⎞ RIGHT PARENTHESIS UPPER HOOK
        '\u{23a0}' => Some(0x08ae), //              botrightparens ⎠ RIGHT PARENTHESIS LOWER HOOK
        '\u{23a8}' => Some(0x08af), //        leftmiddlecurlybrace ⎨ LEFT CURLY BRACKET MIDDLE PIECE
        '\u{23ac}' => Some(0x08b0), //       rightmiddlecurlybrace ⎬ RIGHT CURLY BRACKET MIDDLE PIECE
        '\u{2264}' => Some(0x08bc), //               lessthanequal ≤ LESS-THAN OR EQUAL TO
        '\u{2260}' => Some(0x08bd), //                    notequal ≠ NOT EQUAL TO
        '\u{2265}' => Some(0x08be), //            greaterthanequal ≥ GREATER-THAN OR EQUAL TO
        '\u{222b}' => Some(0x08bf), //                    integral ∫ INTEGRAL
        '\u{2234}' => Some(0x08c0), //                   therefore ∴ THEREFORE
        '\u{221d}' => Some(0x08c1), //                   variation ∝ PROPORTIONAL TO
        '\u{221e}' => Some(0x08c2), //                    infinity ∞ INFINITY
        '\u{2207}' => Some(0x08c5), //                       nabla ∇ NABLA
        '\u{223c}' => Some(0x08c8), //                 approximate ∼ TILDE OPERATOR
        '\u{2243}' => Some(0x08c9), //                similarequal ≃ ASYMPTOTICALLY EQUAL TO
        '\u{21d4}' => Some(0x08cd), //                    ifonlyif ⇔ LEFT RIGHT DOUBLE ARROW
        '\u{21d2}' => Some(0x08ce), //                     implies ⇒ RIGHTWARDS DOUBLE ARROW
        '\u{2261}' => Some(0x08cf), //                   identical ≡ IDENTICAL TO
        '\u{221a}' => Some(0x08d6), //                     radical √ SQUARE ROOT
        '\u{2282}' => Some(0x08da), //                  includedin ⊂ SUBSET OF
        '\u{2283}' => Some(0x08db), //                    includes ⊃ SUPERSET OF
        '\u{2229}' => Some(0x08dc), //                intersection ∩ INTERSECTION
        '\u{222a}' => Some(0x08dd), //                       union ∪ UNION
        '\u{2227}' => Some(0x08de), //                  logicaland ∧ LOGICAL AND
        '\u{2228}' => Some(0x08df), //                   logicalor ∨ LOGICAL OR
        '\u{2202}' => Some(0x08ef), //           partialderivative ∂ PARTIAL DIFFERENTIAL
        '\u{0192}' => Some(0x08f6), //                    function ƒ LATIN SMALL LETTER F WITH HOOK
        '\u{2190}' => Some(0x08fb), //                   leftarrow ← LEFTWARDS ARROW
        '\u{2191}' => Some(0x08fc), //                     uparrow ↑ UPWARDS ARROW
        '\u{2192}' => Some(0x08fd), //                  rightarrow → RIGHTWARDS ARROW
        '\u{2193}' => Some(0x08fe), //                   downarrow ↓ DOWNWARDS ARROW
        '\u{2422}' => Some(0x09df), //                       blank ␢ BLANK SYMBOL
        '\u{25c6}' => Some(0x09e0), //                soliddiamond ◆ BLACK DIAMOND
        '\u{2592}' => Some(0x09e1), //                checkerboard ▒ MEDIUM SHADE
        '\u{2409}' => Some(0x09e2), //                          ht ␉ SYMBOL FOR HORIZONTAL TABULATION
        '\u{240c}' => Some(0x09e3), //                          ff ␌ SYMBOL FOR FORM FEED
        '\u{240d}' => Some(0x09e4), //                          cr ␍ SYMBOL FOR CARRIAGE RETURN
        '\u{240a}' => Some(0x09e5), //                          lf ␊ SYMBOL FOR LINE FEED
        '\u{2424}' => Some(0x09e8), //                          nl ␤ SYMBOL FOR NEWLINE
        '\u{240b}' => Some(0x09e9), //                          vt ␋ SYMBOL FOR VERTICAL TABULATION
        '\u{2518}' => Some(0x09ea), //              lowrightcorner ┘ BOX DRAWINGS LIGHT UP AND LEFT
        '\u{2510}' => Some(0x09eb), //               uprightcorner ┐ BOX DRAWINGS LIGHT DOWN AND LEFT
        '\u{250c}' => Some(0x09ec), //                upleftcorner ┌ BOX DRAWINGS LIGHT DOWN AND RIGHT
        '\u{2514}' => Some(0x09ed), //               lowleftcorner └ BOX DRAWINGS LIGHT UP AND RIGHT
        '\u{253c}' => Some(0x09ee), //               crossinglines ┼ BOX DRAWINGS LIGHT VERTICAL AND HORIZONTAL
        '\u{23ba}' => Some(0x09ef), //              horizlinescan1 ⎺ HORIZONTAL SCAN LINE-1
        '\u{23bb}' => Some(0x09f0), //              horizlinescan3 ⎻ HORIZONTAL SCAN LINE-3
        '\u{2500}' => Some(0x09f1), //              horizlinescan5 ─ BOX DRAWINGS LIGHT HORIZONTAL
        '\u{23bc}' => Some(0x09f2), //              horizlinescan7 ⎼ HORIZONTAL SCAN LINE-7
        '\u{23bd}' => Some(0x09f3), //              horizlinescan9 ⎽ HORIZONTAL SCAN LINE-9
        '\u{251c}' => Some(0x09f4), //                       leftt ├ BOX DRAWINGS LIGHT VERTICAL AND RIGHT
        '\u{2524}' => Some(0x09f5), //                      rightt ┤ BOX DRAWINGS LIGHT VERTICAL AND LEFT
        '\u{2534}' => Some(0x09f6), //                        bott ┴ BOX DRAWINGS LIGHT UP AND HORIZONTAL
        '\u{252c}' => Some(0x09f7), //                        topt ┬ BOX DRAWINGS LIGHT DOWN AND HORIZONTAL
        '\u{2502}' => Some(0x09f8), //                     vertbar │ BOX DRAWINGS LIGHT VERTICAL
        '\u{2003}' => Some(0x0aa1), //                     emspace   EM SPACE
        '\u{2002}' => Some(0x0aa2), //                     enspace   EN SPACE
        '\u{2004}' => Some(0x0aa3), //                    em3space   THREE-PER-EM SPACE
        '\u{2005}' => Some(0x0aa4), //                    em4space   FOUR-PER-EM SPACE
        '\u{2007}' => Some(0x0aa5), //                  digitspace   FIGURE SPACE
        '\u{2008}' => Some(0x0aa6), //                  punctspace   PUNCTUATION SPACE
        '\u{2009}' => Some(0x0aa7), //                   thinspace   THIN SPACE
        '\u{200a}' => Some(0x0aa8), //                   hairspace   HAIR SPACE
        '\u{2014}' => Some(0x0aa9), //                      emdash — EM DASH
        '\u{2013}' => Some(0x0aaa), //                      endash – EN DASH
        '\u{2423}' => Some(0x0aac), //                 signifblank ␣ OPEN BOX
        '\u{2026}' => Some(0x0aae), //                    ellipsis … HORIZONTAL ELLIPSIS
        '\u{2025}' => Some(0x0aaf), //             doubbaselinedot ‥ TWO DOT LEADER
        '\u{2153}' => Some(0x0ab0), //                    onethird ⅓ VULGAR FRACTION ONE THIRD
        '\u{2154}' => Some(0x0ab1), //                   twothirds ⅔ VULGAR FRACTION TWO THIRDS
        '\u{2155}' => Some(0x0ab2), //                    onefifth ⅕ VULGAR FRACTION ONE FIFTH
        '\u{2156}' => Some(0x0ab3), //                   twofifths ⅖ VULGAR FRACTION TWO FIFTHS
        '\u{2157}' => Some(0x0ab4), //                 threefifths ⅗ VULGAR FRACTION THREE FIFTHS
        '\u{2158}' => Some(0x0ab5), //                  fourfifths ⅘ VULGAR FRACTION FOUR FIFTHS
        '\u{2159}' => Some(0x0ab6), //                    onesixth ⅙ VULGAR FRACTION ONE SIXTH
        '\u{215a}' => Some(0x0ab7), //                  fivesixths ⅚ VULGAR FRACTION FIVE SIXTHS
        '\u{2105}' => Some(0x0ab8), //                      careof ℅ CARE OF
        '\u{2012}' => Some(0x0abb), //                     figdash ‒ FIGURE DASH
        '\u{2329}' => Some(0x0abc), //            leftanglebracket 〈 LEFT-POINTING ANGLE BRACKET
        '\u{002e}' => Some(0x0abd), //                decimalpoint . FULL STOP
        '\u{232a}' => Some(0x0abe), //           rightanglebracket 〉 RIGHT-POINTING ANGLE BRACKET
        '\u{215b}' => Some(0x0ac3), //                   oneeighth ⅛ VULGAR FRACTION ONE EIGHTH
        '\u{215c}' => Some(0x0ac4), //                threeeighths ⅜ VULGAR FRACTION THREE EIGHTHS
        '\u{215d}' => Some(0x0ac5), //                 fiveeighths ⅝ VULGAR FRACTION FIVE EIGHTHS
        '\u{215e}' => Some(0x0ac6), //                seveneighths ⅞ VULGAR FRACTION SEVEN EIGHTHS
        '\u{2122}' => Some(0x0ac9), //                   trademark ™ TRADE MARK SIGN
        '\u{2613}' => Some(0x0aca), //               signaturemark ☓ SALTIRE
        '\u{25c1}' => Some(0x0acc), //            leftopentriangle ◁ WHITE LEFT-POINTING TRIANGLE
        '\u{25b7}' => Some(0x0acd), //           rightopentriangle ▷ WHITE RIGHT-POINTING TRIANGLE
        '\u{25cb}' => Some(0x0ace), //                emopencircle ○ WHITE CIRCLE
        '\u{25af}' => Some(0x0acf), //             emopenrectangle ▯ WHITE VERTICAL RECTANGLE
        '\u{2018}' => Some(0x0ad0), //         leftsinglequotemark ‘ LEFT SINGLE QUOTATION MARK
        '\u{2019}' => Some(0x0ad1), //        rightsinglequotemark ’ RIGHT SINGLE QUOTATION MARK
        '\u{201c}' => Some(0x0ad2), //         leftdoublequotemark “ LEFT DOUBLE QUOTATION MARK
        '\u{201d}' => Some(0x0ad3), //        rightdoublequotemark ” RIGHT DOUBLE QUOTATION MARK
        '\u{211e}' => Some(0x0ad4), //                prescription ℞ PRESCRIPTION TAKE
        '\u{2032}' => Some(0x0ad6), //                     minutes ′ PRIME
        '\u{2033}' => Some(0x0ad7), //                     seconds ″ DOUBLE PRIME
        '\u{271d}' => Some(0x0ad9), //                  latincross ✝ LATIN CROSS
        '\u{25ac}' => Some(0x0adb), //            filledrectbullet ▬ BLACK RECTANGLE
        '\u{25c0}' => Some(0x0adc), //         filledlefttribullet ◀ BLACK LEFT-POINTING TRIANGLE
        '\u{25b6}' => Some(0x0add), //        filledrighttribullet ▶ BLACK RIGHT-POINTING TRIANGLE
        '\u{25cf}' => Some(0x0ade), //              emfilledcircle ● BLACK CIRCLE
        '\u{25ae}' => Some(0x0adf), //                emfilledrect ▮ BLACK VERTICAL RECTANGLE
        '\u{25e6}' => Some(0x0ae0), //            enopencircbullet ◦ WHITE BULLET
        '\u{25ab}' => Some(0x0ae1), //          enopensquarebullet ▫ WHITE SMALL SQUARE
        '\u{25ad}' => Some(0x0ae2), //              openrectbullet ▭ WHITE RECTANGLE
        '\u{25b3}' => Some(0x0ae3), //             opentribulletup △ WHITE UP-POINTING TRIANGLE
        '\u{25bd}' => Some(0x0ae4), //           opentribulletdown ▽ WHITE DOWN-POINTING TRIANGLE
        '\u{2606}' => Some(0x0ae5), //                    openstar ☆ WHITE STAR
        '\u{2022}' => Some(0x0ae6), //          enfilledcircbullet • BULLET
        '\u{25aa}' => Some(0x0ae7), //            enfilledsqbullet ▪ BLACK SMALL SQUARE
        '\u{25b2}' => Some(0x0ae8), //           filledtribulletup ▲ BLACK UP-POINTING TRIANGLE
        '\u{25bc}' => Some(0x0ae9), //         filledtribulletdown ▼ BLACK DOWN-POINTING TRIANGLE
        '\u{261c}' => Some(0x0aea), //                 leftpointer ☜ WHITE LEFT POINTING INDEX
        '\u{261e}' => Some(0x0aeb), //                rightpointer ☞ WHITE RIGHT POINTING INDEX
        '\u{2663}' => Some(0x0aec), //                        club ♣ BLACK CLUB SUIT
        '\u{2666}' => Some(0x0aed), //                     diamond ♦ BLACK DIAMOND SUIT
        '\u{2665}' => Some(0x0aee), //                       heart ♥ BLACK HEART SUIT
        '\u{2720}' => Some(0x0af0), //                maltesecross ✠ MALTESE CROSS
        '\u{2020}' => Some(0x0af1), //                      dagger † DAGGER
        '\u{2021}' => Some(0x0af2), //                doubledagger ‡ DOUBLE DAGGER
        '\u{2713}' => Some(0x0af3), //                   checkmark ✓ CHECK MARK
        '\u{2717}' => Some(0x0af4), //                 ballotcross ✗ BALLOT X
        '\u{266f}' => Some(0x0af5), //                musicalsharp ♯ MUSIC SHARP SIGN
        '\u{266d}' => Some(0x0af6), //                 musicalflat ♭ MUSIC FLAT SIGN
        '\u{2642}' => Some(0x0af7), //                  malesymbol ♂ MALE SIGN
        '\u{2640}' => Some(0x0af8), //                femalesymbol ♀ FEMALE SIGN
        '\u{260e}' => Some(0x0af9), //                   telephone ☎ BLACK TELEPHONE
        '\u{2315}' => Some(0x0afa), //           telephonerecorder ⌕ TELEPHONE RECORDER
        '\u{2117}' => Some(0x0afb), //         phonographcopyright ℗ SOUND RECORDING COPYRIGHT
        '\u{2038}' => Some(0x0afc), //                       caret ‸ CARET
        '\u{201a}' => Some(0x0afd), //          singlelowquotemark ‚ SINGLE LOW-9 QUOTATION MARK
        '\u{201e}' => Some(0x0afe), //          doublelowquotemark „ DOUBLE LOW-9 QUOTATION MARK
        '\u{003c}' => Some(0x0ba3), //                   leftcaret < LESS-THAN SIGN
        '\u{003e}' => Some(0x0ba6), //                  rightcaret > GREATER-THAN SIGN
        '\u{2228}' => Some(0x0ba8), //                   downcaret ∨ LOGICAL OR
        '\u{2227}' => Some(0x0ba9), //                     upcaret ∧ LOGICAL AND
        '\u{00af}' => Some(0x0bc0), //                     overbar ¯ MACRON
        '\u{22a5}' => Some(0x0bc2), //                    downtack ⊥ UP TACK
        '\u{2229}' => Some(0x0bc3), //                      upshoe ∩ INTERSECTION
        '\u{230a}' => Some(0x0bc4), //                   downstile ⌊ LEFT FLOOR
        '\u{005f}' => Some(0x0bc6), //                    underbar _ LOW LINE
        '\u{2218}' => Some(0x0bca), //                         jot ∘ RING OPERATOR
        '\u{2395}' => Some(0x0bcc), //                        quad ⎕ APL FUNCTIONAL SYMBOL QUAD
        '\u{22a4}' => Some(0x0bce), //                      uptack ⊤ DOWN TACK
        '\u{25cb}' => Some(0x0bcf), //                      circle ○ WHITE CIRCLE
        '\u{2308}' => Some(0x0bd3), //                     upstile ⌈ LEFT CEILING
        '\u{222a}' => Some(0x0bd6), //                    downshoe ∪ UNION
        '\u{2283}' => Some(0x0bd8), //                   rightshoe ⊃ SUPERSET OF
        '\u{2282}' => Some(0x0bda), //                    leftshoe ⊂ SUBSET OF
        '\u{22a2}' => Some(0x0bdc), //                    lefttack ⊢ RIGHT TACK
        '\u{22a3}' => Some(0x0bfc), //                   righttack ⊣ LEFT TACK
        '\u{2017}' => Some(0x0cdf), //        hebrew_doublelowline ‗ DOUBLE LOW LINE
        '\u{05d0}' => Some(0x0ce0), //                hebrew_aleph א HEBREW LETTER ALEF
        '\u{05d1}' => Some(0x0ce1), //                  hebrew_bet ב HEBREW LETTER BET
        '\u{05d2}' => Some(0x0ce2), //                hebrew_gimel ג HEBREW LETTER GIMEL
        '\u{05d3}' => Some(0x0ce3), //                hebrew_dalet ד HEBREW LETTER DALET
        '\u{05d4}' => Some(0x0ce4), //                   hebrew_he ה HEBREW LETTER HE
        '\u{05d5}' => Some(0x0ce5), //                  hebrew_waw ו HEBREW LETTER VAV
        '\u{05d6}' => Some(0x0ce6), //                 hebrew_zain ז HEBREW LETTER ZAYIN
        '\u{05d7}' => Some(0x0ce7), //                 hebrew_chet ח HEBREW LETTER HET
        '\u{05d8}' => Some(0x0ce8), //                  hebrew_tet ט HEBREW LETTER TET
        '\u{05d9}' => Some(0x0ce9), //                  hebrew_yod י HEBREW LETTER YOD
        '\u{05da}' => Some(0x0cea), //            hebrew_finalkaph ך HEBREW LETTER FINAL KAF
        '\u{05db}' => Some(0x0ceb), //                 hebrew_kaph כ HEBREW LETTER KAF
        '\u{05dc}' => Some(0x0cec), //                hebrew_lamed ל HEBREW LETTER LAMED
        '\u{05dd}' => Some(0x0ced), //             hebrew_finalmem ם HEBREW LETTER FINAL MEM
        '\u{05de}' => Some(0x0cee), //                  hebrew_mem מ HEBREW LETTER MEM
        '\u{05df}' => Some(0x0cef), //             hebrew_finalnun ן HEBREW LETTER FINAL NUN
        '\u{05e0}' => Some(0x0cf0), //                  hebrew_nun נ HEBREW LETTER NUN
        '\u{05e1}' => Some(0x0cf1), //               hebrew_samech ס HEBREW LETTER SAMEKH
        '\u{05e2}' => Some(0x0cf2), //                 hebrew_ayin ע HEBREW LETTER AYIN
        '\u{05e3}' => Some(0x0cf3), //              hebrew_finalpe ף HEBREW LETTER FINAL PE
        '\u{05e4}' => Some(0x0cf4), //                   hebrew_pe פ HEBREW LETTER PE
        '\u{05e5}' => Some(0x0cf5), //            hebrew_finalzade ץ HEBREW LETTER FINAL TSADI
        '\u{05e6}' => Some(0x0cf6), //                 hebrew_zade צ HEBREW LETTER TSADI
        '\u{05e7}' => Some(0x0cf7), //                 hebrew_qoph ק HEBREW LETTER QOF
        '\u{05e8}' => Some(0x0cf8), //                 hebrew_resh ר HEBREW LETTER RESH
        '\u{05e9}' => Some(0x0cf9), //                 hebrew_shin ש HEBREW LETTER SHIN
        '\u{05ea}' => Some(0x0cfa), //                  hebrew_taw ת HEBREW LETTER TAV
        '\u{0e01}' => Some(0x0da1), //                  Thai_kokai ก THAI CHARACTER KO KAI
        '\u{0e02}' => Some(0x0da2), //                Thai_khokhai ข THAI CHARACTER KHO KHAI
        '\u{0e03}' => Some(0x0da3), //               Thai_khokhuat ฃ THAI CHARACTER KHO KHUAT
        '\u{0e04}' => Some(0x0da4), //               Thai_khokhwai ค THAI CHARACTER KHO KHWAI
        '\u{0e05}' => Some(0x0da5), //                Thai_khokhon ฅ THAI CHARACTER KHO KHON
        '\u{0e06}' => Some(0x0da6), //             Thai_khorakhang ฆ THAI CHARACTER KHO RAKHANG
        '\u{0e07}' => Some(0x0da7), //                 Thai_ngongu ง THAI CHARACTER NGO NGU
        '\u{0e08}' => Some(0x0da8), //                Thai_chochan จ THAI CHARACTER CHO CHAN
        '\u{0e09}' => Some(0x0da9), //               Thai_choching ฉ THAI CHARACTER CHO CHING
        '\u{0e0a}' => Some(0x0daa), //               Thai_chochang ช THAI CHARACTER CHO CHANG
        '\u{0e0b}' => Some(0x0dab), //                   Thai_soso ซ THAI CHARACTER SO SO
        '\u{0e0c}' => Some(0x0dac), //                Thai_chochoe ฌ THAI CHARACTER CHO CHOE
        '\u{0e0d}' => Some(0x0dad), //                 Thai_yoying ญ THAI CHARACTER YO YING
        '\u{0e0e}' => Some(0x0dae), //                Thai_dochada ฎ THAI CHARACTER DO CHADA
        '\u{0e0f}' => Some(0x0daf), //                Thai_topatak ฏ THAI CHARACTER TO PATAK
        '\u{0e10}' => Some(0x0db0), //                Thai_thothan ฐ THAI CHARACTER THO THAN
        '\u{0e11}' => Some(0x0db1), //          Thai_thonangmontho ฑ THAI CHARACTER THO NANGMONTHO
        '\u{0e12}' => Some(0x0db2), //             Thai_thophuthao ฒ THAI CHARACTER THO PHUTHAO
        '\u{0e13}' => Some(0x0db3), //                  Thai_nonen ณ THAI CHARACTER NO NEN
        '\u{0e14}' => Some(0x0db4), //                  Thai_dodek ด THAI CHARACTER DO DEK
        '\u{0e15}' => Some(0x0db5), //                  Thai_totao ต THAI CHARACTER TO TAO
        '\u{0e16}' => Some(0x0db6), //               Thai_thothung ถ THAI CHARACTER THO THUNG
        '\u{0e17}' => Some(0x0db7), //              Thai_thothahan ท THAI CHARACTER THO THAHAN
        '\u{0e18}' => Some(0x0db8), //               Thai_thothong ธ THAI CHARACTER THO THONG
        '\u{0e19}' => Some(0x0db9), //                   Thai_nonu น THAI CHARACTER NO NU
        '\u{0e1a}' => Some(0x0dba), //               Thai_bobaimai บ THAI CHARACTER BO BAIMAI
        '\u{0e1b}' => Some(0x0dbb), //                  Thai_popla ป THAI CHARACTER PO PLA
        '\u{0e1c}' => Some(0x0dbc), //               Thai_phophung ผ THAI CHARACTER PHO PHUNG
        '\u{0e1d}' => Some(0x0dbd), //                   Thai_fofa ฝ THAI CHARACTER FO FA
        '\u{0e1e}' => Some(0x0dbe), //                Thai_phophan พ THAI CHARACTER PHO PHAN
        '\u{0e1f}' => Some(0x0dbf), //                  Thai_fofan ฟ THAI CHARACTER FO FAN
        '\u{0e20}' => Some(0x0dc0), //             Thai_phosamphao ภ THAI CHARACTER PHO SAMPHAO
        '\u{0e21}' => Some(0x0dc1), //                   Thai_moma ม THAI CHARACTER MO MA
        '\u{0e22}' => Some(0x0dc2), //                  Thai_yoyak ย THAI CHARACTER YO YAK
        '\u{0e23}' => Some(0x0dc3), //                  Thai_rorua ร THAI CHARACTER RO RUA
        '\u{0e24}' => Some(0x0dc4), //                     Thai_ru ฤ THAI CHARACTER RU
        '\u{0e25}' => Some(0x0dc5), //                 Thai_loling ล THAI CHARACTER LO LING
        '\u{0e26}' => Some(0x0dc6), //                     Thai_lu ฦ THAI CHARACTER LU
        '\u{0e27}' => Some(0x0dc7), //                 Thai_wowaen ว THAI CHARACTER WO WAEN
        '\u{0e28}' => Some(0x0dc8), //                 Thai_sosala ศ THAI CHARACTER SO SALA
        '\u{0e29}' => Some(0x0dc9), //                 Thai_sorusi ษ THAI CHARACTER SO RUSI
        '\u{0e2a}' => Some(0x0dca), //                  Thai_sosua ส THAI CHARACTER SO SUA
        '\u{0e2b}' => Some(0x0dcb), //                  Thai_hohip ห THAI CHARACTER HO HIP
        '\u{0e2c}' => Some(0x0dcc), //                Thai_lochula ฬ THAI CHARACTER LO CHULA
        '\u{0e2d}' => Some(0x0dcd), //                   Thai_oang อ THAI CHARACTER O ANG
        '\u{0e2e}' => Some(0x0dce), //               Thai_honokhuk ฮ THAI CHARACTER HO NOKHUK
        '\u{0e2f}' => Some(0x0dcf), //              Thai_paiyannoi ฯ THAI CHARACTER PAIYANNOI
        '\u{0e30}' => Some(0x0dd0), //                  Thai_saraa ะ THAI CHARACTER SARA A
        '\u{0e31}' => Some(0x0dd1), //             Thai_maihanakat ั THAI CHARACTER MAI HAN-AKAT
        '\u{0e32}' => Some(0x0dd2), //                 Thai_saraaa า THAI CHARACTER SARA AA
        '\u{0e33}' => Some(0x0dd3), //                 Thai_saraam ำ THAI CHARACTER SARA AM
        '\u{0e34}' => Some(0x0dd4), //                  Thai_sarai ิ THAI CHARACTER SARA I
        '\u{0e35}' => Some(0x0dd5), //                 Thai_saraii ี THAI CHARACTER SARA II
        '\u{0e36}' => Some(0x0dd6), //                 Thai_saraue ึ THAI CHARACTER SARA UE
        '\u{0e37}' => Some(0x0dd7), //                Thai_sarauee ื THAI CHARACTER SARA UEE
        '\u{0e38}' => Some(0x0dd8), //                  Thai_sarau ุ THAI CHARACTER SARA U
        '\u{0e39}' => Some(0x0dd9), //                 Thai_sarauu ู THAI CHARACTER SARA UU
        '\u{0e3a}' => Some(0x0dda), //                Thai_phinthu ฺ THAI CHARACTER PHINTHU
        '\u{0e3e}' => Some(0x0dde), //      Thai_maihanakat_maitho ฾ ???
        '\u{0e3f}' => Some(0x0ddf), //                   Thai_baht ฿ THAI CURRENCY SYMBOL BAHT
        '\u{0e40}' => Some(0x0de0), //                  Thai_sarae เ THAI CHARACTER SARA E
        '\u{0e41}' => Some(0x0de1), //                 Thai_saraae แ THAI CHARACTER SARA AE
        '\u{0e42}' => Some(0x0de2), //                  Thai_sarao โ THAI CHARACTER SARA O
        '\u{0e43}' => Some(0x0de3), //          Thai_saraaimaimuan ใ THAI CHARACTER SARA AI MAIMUAN
        '\u{0e44}' => Some(0x0de4), //         Thai_saraaimaimalai ไ THAI CHARACTER SARA AI MAIMALAI
        '\u{0e45}' => Some(0x0de5), //            Thai_lakkhangyao ๅ THAI CHARACTER LAKKHANGYAO
        '\u{0e46}' => Some(0x0de6), //               Thai_maiyamok ๆ THAI CHARACTER MAIYAMOK
        '\u{0e47}' => Some(0x0de7), //              Thai_maitaikhu ็ THAI CHARACTER MAITAIKHU
        '\u{0e48}' => Some(0x0de8), //                  Thai_maiek ่ THAI CHARACTER MAI EK
        '\u{0e49}' => Some(0x0de9), //                 Thai_maitho ้ THAI CHARACTER MAI THO
        '\u{0e4a}' => Some(0x0dea), //                 Thai_maitri ๊ THAI CHARACTER MAI TRI
        '\u{0e4b}' => Some(0x0deb), //            Thai_maichattawa ๋ THAI CHARACTER MAI CHATTAWA
        '\u{0e4c}' => Some(0x0dec), //            Thai_thanthakhat ์ THAI CHARACTER THANTHAKHAT
        '\u{0e4d}' => Some(0x0ded), //               Thai_nikhahit ํ THAI CHARACTER NIKHAHIT
        '\u{0e50}' => Some(0x0df0), //                 Thai_leksun ๐ THAI DIGIT ZERO
        '\u{0e51}' => Some(0x0df1), //                Thai_leknung ๑ THAI DIGIT ONE
        '\u{0e52}' => Some(0x0df2), //                Thai_leksong ๒ THAI DIGIT TWO
        '\u{0e53}' => Some(0x0df3), //                 Thai_leksam ๓ THAI DIGIT THREE
        '\u{0e54}' => Some(0x0df4), //                  Thai_leksi ๔ THAI DIGIT FOUR
        '\u{0e55}' => Some(0x0df5), //                  Thai_lekha ๕ THAI DIGIT FIVE
        '\u{0e56}' => Some(0x0df6), //                 Thai_lekhok ๖ THAI DIGIT SIX
        '\u{0e57}' => Some(0x0df7), //                Thai_lekchet ๗ THAI DIGIT SEVEN
        '\u{0e58}' => Some(0x0df8), //                Thai_lekpaet ๘ THAI DIGIT EIGHT
        '\u{0e59}' => Some(0x0df9), //                 Thai_lekkao ๙ THAI DIGIT NINE
        '\u{3131}' => Some(0x0ea1), //               Hangul_Kiyeog ㄱ HANGUL LETTER KIYEOK
        '\u{3132}' => Some(0x0ea2), //          Hangul_SsangKiyeog ㄲ HANGUL LETTER SSANGKIYEOK
        '\u{3133}' => Some(0x0ea3), //           Hangul_KiyeogSios ㄳ HANGUL LETTER KIYEOK-SIOS
        '\u{3134}' => Some(0x0ea4), //                Hangul_Nieun ㄴ HANGUL LETTER NIEUN
        '\u{3135}' => Some(0x0ea5), //           Hangul_NieunJieuj ㄵ HANGUL LETTER NIEUN-CIEUC
        '\u{3136}' => Some(0x0ea6), //           Hangul_NieunHieuh ㄶ HANGUL LETTER NIEUN-HIEUH
        '\u{3137}' => Some(0x0ea7), //               Hangul_Dikeud ㄷ HANGUL LETTER TIKEUT
        '\u{3138}' => Some(0x0ea8), //          Hangul_SsangDikeud ㄸ HANGUL LETTER SSANGTIKEUT
        '\u{3139}' => Some(0x0ea9), //                Hangul_Rieul ㄹ HANGUL LETTER RIEUL
        '\u{313a}' => Some(0x0eaa), //          Hangul_RieulKiyeog ㄺ HANGUL LETTER RIEUL-KIYEOK
        '\u{313b}' => Some(0x0eab), //           Hangul_RieulMieum ㄻ HANGUL LETTER RIEUL-MIEUM
        '\u{313c}' => Some(0x0eac), //           Hangul_RieulPieub ㄼ HANGUL LETTER RIEUL-PIEUP
        '\u{313d}' => Some(0x0ead), //            Hangul_RieulSios ㄽ HANGUL LETTER RIEUL-SIOS
        '\u{313e}' => Some(0x0eae), //           Hangul_RieulTieut ㄾ HANGUL LETTER RIEUL-THIEUTH
        '\u{313f}' => Some(0x0eaf), //          Hangul_RieulPhieuf ㄿ HANGUL LETTER RIEUL-PHIEUPH
        '\u{3140}' => Some(0x0eb0), //           Hangul_RieulHieuh ㅀ HANGUL LETTER RIEUL-HIEUH
        '\u{3141}' => Some(0x0eb1), //                Hangul_Mieum ㅁ HANGUL LETTER MIEUM
        '\u{3142}' => Some(0x0eb2), //                Hangul_Pieub ㅂ HANGUL LETTER PIEUP
        '\u{3143}' => Some(0x0eb3), //           Hangul_SsangPieub ㅃ HANGUL LETTER SSANGPIEUP
        '\u{3144}' => Some(0x0eb4), //            Hangul_PieubSios ㅄ HANGUL LETTER PIEUP-SIOS
        '\u{3145}' => Some(0x0eb5), //                 Hangul_Sios ㅅ HANGUL LETTER SIOS
        '\u{3146}' => Some(0x0eb6), //            Hangul_SsangSios ㅆ HANGUL LETTER SSANGSIOS
        '\u{3147}' => Some(0x0eb7), //                Hangul_Ieung ㅇ HANGUL LETTER IEUNG
        '\u{3148}' => Some(0x0eb8), //                Hangul_Jieuj ㅈ HANGUL LETTER CIEUC
        '\u{3149}' => Some(0x0eb9), //           Hangul_SsangJieuj ㅉ HANGUL LETTER SSANGCIEUC
        '\u{314a}' => Some(0x0eba), //                Hangul_Cieuc ㅊ HANGUL LETTER CHIEUCH
        '\u{314b}' => Some(0x0ebb), //               Hangul_Khieuq ㅋ HANGUL LETTER KHIEUKH
        '\u{314c}' => Some(0x0ebc), //                Hangul_Tieut ㅌ HANGUL LETTER THIEUTH
        '\u{314d}' => Some(0x0ebd), //               Hangul_Phieuf ㅍ HANGUL LETTER PHIEUPH
        '\u{314e}' => Some(0x0ebe), //                Hangul_Hieuh ㅎ HANGUL LETTER HIEUH
        '\u{314f}' => Some(0x0ebf), //                    Hangul_A ㅏ HANGUL LETTER A
        '\u{3150}' => Some(0x0ec0), //                   Hangul_AE ㅐ HANGUL LETTER AE
        '\u{3151}' => Some(0x0ec1), //                   Hangul_YA ㅑ HANGUL LETTER YA
        '\u{3152}' => Some(0x0ec2), //                  Hangul_YAE ㅒ HANGUL LETTER YAE
        '\u{3153}' => Some(0x0ec3), //                   Hangul_EO ㅓ HANGUL LETTER EO
        '\u{3154}' => Some(0x0ec4), //                    Hangul_E ㅔ HANGUL LETTER E
        '\u{3155}' => Some(0x0ec5), //                  Hangul_YEO ㅕ HANGUL LETTER YEO
        '\u{3156}' => Some(0x0ec6), //                   Hangul_YE ㅖ HANGUL LETTER YE
        '\u{3157}' => Some(0x0ec7), //                    Hangul_O ㅗ HANGUL LETTER O
        '\u{3158}' => Some(0x0ec8), //                   Hangul_WA ㅘ HANGUL LETTER WA
        '\u{3159}' => Some(0x0ec9), //                  Hangul_WAE ㅙ HANGUL LETTER WAE
        '\u{315a}' => Some(0x0eca), //                   Hangul_OE ㅚ HANGUL LETTER OE
        '\u{315b}' => Some(0x0ecb), //                   Hangul_YO ㅛ HANGUL LETTER YO
        '\u{315c}' => Some(0x0ecc), //                    Hangul_U ㅜ HANGUL LETTER U
        '\u{315d}' => Some(0x0ecd), //                  Hangul_WEO ㅝ HANGUL LETTER WEO
        '\u{315e}' => Some(0x0ece), //                   Hangul_WE ㅞ HANGUL LETTER WE
        '\u{315f}' => Some(0x0ecf), //                   Hangul_WI ㅟ HANGUL LETTER WI
        '\u{3160}' => Some(0x0ed0), //                   Hangul_YU ㅠ HANGUL LETTER YU
        '\u{3161}' => Some(0x0ed1), //                   Hangul_EU ㅡ HANGUL LETTER EU
        '\u{3162}' => Some(0x0ed2), //                   Hangul_YI ㅢ HANGUL LETTER YI
        '\u{3163}' => Some(0x0ed3), //                    Hangul_I ㅣ HANGUL LETTER I
        '\u{11a8}' => Some(0x0ed4), //             Hangul_J_Kiyeog ᆨ HANGUL JONGSEONG KIYEOK
        '\u{11a9}' => Some(0x0ed5), //        Hangul_J_SsangKiyeog ᆩ HANGUL JONGSEONG SSANGKIYEOK
        '\u{11aa}' => Some(0x0ed6), //         Hangul_J_KiyeogSios ᆪ HANGUL JONGSEONG KIYEOK-SIOS
        '\u{11ab}' => Some(0x0ed7), //              Hangul_J_Nieun ᆫ HANGUL JONGSEONG NIEUN
        '\u{11ac}' => Some(0x0ed8), //         Hangul_J_NieunJieuj ᆬ HANGUL JONGSEONG NIEUN-CIEUC
        '\u{11ad}' => Some(0x0ed9), //         Hangul_J_NieunHieuh ᆭ HANGUL JONGSEONG NIEUN-HIEUH
        '\u{11ae}' => Some(0x0eda), //             Hangul_J_Dikeud ᆮ HANGUL JONGSEONG TIKEUT
        '\u{11af}' => Some(0x0edb), //              Hangul_J_Rieul ᆯ HANGUL JONGSEONG RIEUL
        '\u{11b0}' => Some(0x0edc), //        Hangul_J_RieulKiyeog ᆰ HANGUL JONGSEONG RIEUL-KIYEOK
        '\u{11b1}' => Some(0x0edd), //         Hangul_J_RieulMieum ᆱ HANGUL JONGSEONG RIEUL-MIEUM
        '\u{11b2}' => Some(0x0ede), //         Hangul_J_RieulPieub ᆲ HANGUL JONGSEONG RIEUL-PIEUP
        '\u{11b3}' => Some(0x0edf), //          Hangul_J_RieulSios ᆳ HANGUL JONGSEONG RIEUL-SIOS
        '\u{11b4}' => Some(0x0ee0), //         Hangul_J_RieulTieut ᆴ HANGUL JONGSEONG RIEUL-THIEUTH
        '\u{11b5}' => Some(0x0ee1), //        Hangul_J_RieulPhieuf ᆵ HANGUL JONGSEONG RIEUL-PHIEUPH
        '\u{11b6}' => Some(0x0ee2), //         Hangul_J_RieulHieuh ᆶ HANGUL JONGSEONG RIEUL-HIEUH
        '\u{11b7}' => Some(0x0ee3), //              Hangul_J_Mieum ᆷ HANGUL JONGSEONG MIEUM
        '\u{11b8}' => Some(0x0ee4), //              Hangul_J_Pieub ᆸ HANGUL JONGSEONG PIEUP
        '\u{11b9}' => Some(0x0ee5), //          Hangul_J_PieubSios ᆹ HANGUL JONGSEONG PIEUP-SIOS
        '\u{11ba}' => Some(0x0ee6), //               Hangul_J_Sios ᆺ HANGUL JONGSEONG SIOS
        '\u{11bb}' => Some(0x0ee7), //          Hangul_J_SsangSios ᆻ HANGUL JONGSEONG SSANGSIOS
        '\u{11bc}' => Some(0x0ee8), //              Hangul_J_Ieung ᆼ HANGUL JONGSEONG IEUNG
        '\u{11bd}' => Some(0x0ee9), //              Hangul_J_Jieuj ᆽ HANGUL JONGSEONG CIEUC
        '\u{11be}' => Some(0x0eea), //              Hangul_J_Cieuc ᆾ HANGUL JONGSEONG CHIEUCH
        '\u{11bf}' => Some(0x0eeb), //             Hangul_J_Khieuq ᆿ HANGUL JONGSEONG KHIEUKH
        '\u{11c0}' => Some(0x0eec), //              Hangul_J_Tieut ᇀ HANGUL JONGSEONG THIEUTH
        '\u{11c1}' => Some(0x0eed), //             Hangul_J_Phieuf ᇁ HANGUL JONGSEONG PHIEUPH
        '\u{11c2}' => Some(0x0eee), //              Hangul_J_Hieuh ᇂ HANGUL JONGSEONG HIEUH
        '\u{316d}' => Some(0x0eef), //     Hangul_RieulYeorinHieuh ㅭ HANGUL LETTER RIEUL-YEORINHIEUH
        '\u{3171}' => Some(0x0ef0), //    Hangul_SunkyeongeumMieum ㅱ HANGUL LETTER KAPYEOUNMIEUM
        '\u{3178}' => Some(0x0ef1), //    Hangul_SunkyeongeumPieub ㅸ HANGUL LETTER KAPYEOUNPIEUP
        '\u{317f}' => Some(0x0ef2), //              Hangul_PanSios ㅿ HANGUL LETTER PANSIOS
        '\u{3181}' => Some(0x0ef3), //    Hangul_KkogjiDalrinIeung ㆁ HANGUL LETTER YESIEUNG
        '\u{3184}' => Some(0x0ef4), //   Hangul_SunkyeongeumPhieuf ㆄ HANGUL LETTER KAPYEOUNPHIEUPH
        '\u{3186}' => Some(0x0ef5), //          Hangul_YeorinHieuh ㆆ HANGUL LETTER YEORINHIEUH
        '\u{318d}' => Some(0x0ef6), //                Hangul_AraeA ㆍ HANGUL LETTER ARAEA
        '\u{318e}' => Some(0x0ef7), //               Hangul_AraeAE ㆎ HANGUL LETTER ARAEAE
        '\u{11eb}' => Some(0x0ef8), //            Hangul_J_PanSios ᇫ HANGUL JONGSEONG PANSIOS
        '\u{11f0}' => Some(0x0ef9), //  Hangul_J_KkogjiDalrinIeung ᇰ HANGUL JONGSEONG YESIEUNG
        '\u{11f9}' => Some(0x0efa), //        Hangul_J_YeorinHieuh ᇹ HANGUL JONGSEONG YEORINHIEUH
        '\u{20a9}' => Some(0x0eff), //                  Korean_Won ₩ WON SIGN
        '\u{20ac}' => Some(0x13a4), //                        Euro € EURO SIGN
        '\u{0152}' => Some(0x13bc), //                          OE Œ LATIN CAPITAL LIGATURE OE
        '\u{0153}' => Some(0x13bd), //                          oe œ LATIN SMALL LIGATURE OE
        '\u{0178}' => Some(0x13be), //                  Ydiaeresis Ÿ LATIN CAPITAL LETTER Y WITH DIAERESIS
        '\u{20a0}' => Some(0x20a0), //                     EcuSign ₠ EURO-CURRENCY SIGN
        '\u{20a1}' => Some(0x20a1), //                   ColonSign ₡ COLON SIGN
        '\u{20a2}' => Some(0x20a2), //                CruzeiroSign ₢ CRUZEIRO SIGN
        '\u{20a3}' => Some(0x20a3), //                  FFrancSign ₣ FRENCH FRANC SIGN
        '\u{20a4}' => Some(0x20a4), //                    LiraSign ₤ LIRA SIGN
        '\u{20a5}' => Some(0x20a5), //                    MillSign ₥ MILL SIGN
        '\u{20a6}' => Some(0x20a6), //                   NairaSign ₦ NAIRA SIGN
        '\u{20a7}' => Some(0x20a7), //                  PesetaSign ₧ PESETA SIGN
        '\u{20a8}' => Some(0x20a8), //                   RupeeSign ₨ RUPEE SIGN
        '\u{20a9}' => Some(0x20a9), //                     WonSign ₩ WON SIGN
        '\u{20aa}' => Some(0x20aa), //               NewSheqelSign ₪ NEW SHEQEL SIGN
        '\u{20ab}' => Some(0x20ab), //                    DongSign ₫ DONG SIGN
        '\u{20ac}' => Some(0x20ac), //                    EuroSign € EURO SIGN
        _ => None,
    }
}